### ISSUE TITLE
FastReboot broken

### ISSUE THREAD

**Issue by clarking** [tinkeros/TinkerOS#3]
Hi, I'm experiencing a problem with the FastReboot(BootRam) option of the default personal menu.

Every time i click on the option it reboots but doesn't show the "desktop" again, i got a black window instead with only the first pixel row being painted on the screen (see attached screenshot)

I've tested with a fresh install on C and D drives using 800x600 and 1024x768 resolutions with same results.

![tinkerbug](https://user-images.githubusercontent.com/8283993/128271131-9c40f9e6-8d1e-4ff4-a8f9-6cd0b68360e0.png)

**Comment by tinkeros** [comment]
I agree, it would be good to have this working again.  I'll look into saving the necessary state to allow it to work.

**Comment by tinkeros** [comment]
Please give the version [here](https://github.com/tinkeros/TinkerOS/releases/tag/5.06.5.1) a try and let me know if it resolves your issue.  It works on my end.

**Comment by clarking** [comment]
Yeah, i installed the new ISO on drive D and it worked, thank you!
