### ISSUE TITLE
Psalmody key frequencies

### ISSUE THREAD

**Issue by r4v10l1** [tinkeros/TinkerOS#6]
Hello, first of all I wanted to thank you for making suck a great fork of TempleOS.

I am making my own operative system (not related to TempleOS or HolyC, but still inspired by it) and I just finished adding my own piano app. It's pretty simple but it is able to play frequencies using my own keyboard and pc speaker functions. I was trying to read through your psalmody source code trying to find the pc speaker frequencies being used, but I could not find it since it's hard for me to understand how the program works.

Could you tell me where they are, or if it's more complicated, how it works?

Thank you.

**Comment by tinkeros** [comment]
The code isn't mine, Terry wrote it.  I'll tell you what I know, hopefully it will help you find what you need.  Every note corresponds to an 8-bit value he calls an "ona."  There are two functions that convert between his ona values and frequencies [Ona2Freq](https://tinkeros.github.io/WbGit/Kernel/KMisc.html#l186) and [Freq2Ona](https://tinkeros.github.io/WbGit/Kernel/KMisc.html#l194).  As far as how the songs work, you would want to look at his [Play](https://tinkeros.github.io/WbGit/Adam/Snd/ASnd.html#l234) function where he parses the strings of song notes and converts them into ona values to play.

**Comment by r4v10l1** [comment]
I know Terry wrote the original program, but I didn't know if you made any changes to it.

Looks like `Ona2Freq` and `Freq2Ona` is what I was looking for. I had a look at [this](https://github.com/tinkeros/TinkerOS/blob/55c3aeb5c6c28a051d54f277ea41836d2088363a/Apps/Psalmody/PsalmodyMain.HC#L486-L507) switch statement, but I didn't know what "ona" meant.

Thank you for the quick reply and keep up the good work.

**Comment by r4v10l1** [comment]
I have been messing with the functions and looking at the code and, if I haven't missed anything, these are the psalmody keys, ona values and frequencies:
```
Key:
      +---+---+---+   +---+---+   +---+---+---+
      | E | R | T |   | U | I |   | P | [ | ] |
+---+---+---+---+---+---+---+---+---+---+---+-+
| A | S | D | F | G | H | J | K | L | ; | ' |
+---+---+---+---+---+---+---+---+---+---+---+


Ona:
        +----+----+----+    +----+----+    +----+----+----+
        | 45 | 47 | 49 |    | 52 | 54 |    | 57 | 59 | 61 |
+----+----+----+----+----+----+----+----+----+----+----+--+
| 43 | 44 | 46 | 48 | 50 | 51 | 53 | 55 | 56 | 58 | 60 |
+----+----+----+----+----+----+----+----+----+----+----+


Freq:
         +-----+-----+-----+     +-----+-----+     +-----+-----+-----+
         |184.9|207.6|233.0|     |277.1|311.1|     |369.9|415.3|466.1|
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--+
|164.8|174.6|195.9|220.0|246.9|261.6|293.6|329.6|349.2|391.9|440.0|
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

**Comment by tinkeros** [comment]
These are correct assuming you set octave 3.  The default is octave 4 so for the default condition the app starts in all the ona values above should have 12 added to them and all the frequencies should be double what they are.

**Comment by r4v10l1** [comment]
I thought the default octave was 3, thank you. I am also making my own shell and I just finished argument support, so I will probably make it so my piano app gets the user's octave from there.
