### ISSUE TITLE
Mouse only detecting about half the time

### ISSUE THREAD

**Issue by Dob-The-Duilder** [tinkeros/TinkerOS#7]
I loaded TinkerOS onto a usb to install and the touchpad worked great. However once I installed onto the actual hard drive the ps2 mouse emulation appeared to stop working.

I'm using a Dell Inspiron 5100 if that helps

**Comment by tinkeros** [comment]
Only real PS/2 mice connected to real PS/2 ports are supported currently.  Emulation may or may not work and I have no way to debug it.  You might try running `MsHardRst;` after booting.  On few machines I have where emulation is intermittent that fixes it, but no guarantees it will work for you.
