### ISSUE TITLE
TinkerOS failing to boot

### ISSUE THREAD

**Issue by ogredale** [tinkeros/TinkerOS#8]
I am trying to install TinkerOS in VMware Workstation Pro, but it never boots. It throws an error (see screenshot) then says "Loading compiler" forever.
Screenshot: https://i.imgur.com/unTVhkQ.png

VM specs:
Memory: 4g
Hard disk: 8g
Processor: 4
Network adaptor: Included
Sound card: Included

**Comment by tinkeros** [comment]
It is interesting that in the case of VMware Workstation Pro TempleOS works (by chance) and TinkerOS does not. TempleOS exhibits the same issue on some machines.  I know how to fix this, but I'm not sure when I'll get around to releasing the fix.  For now all I can recommend is that if you see this issue with either TempleOS or TinkerOS that you change the number of processors to 1.

**Comment by ogredale** [comment]
Giving it on processor seems to work, TempleOS has 4 as well but it works fine.

**Comment by tinkeros** [comment]
Don't worry, I got it working, I'll fix it in time for New Years.  Going through my normal QA and rebuild process now before a releasing.  I don't drink alcohol so really I have nothing better to do for New Years anyway.

https://www.youtube.com/watch?v=BL_oRyVF410

**Comment by ogredale** [comment]
Alright, thanks man!

**Comment by tinkeros** [comment]
Please test the latest 5.13 release on your end, it works on my end.

**Comment by ogredale** [comment]
Yup, it works now, also didn't know setting it as DOS would change anything. Cheers.

**Comment by tinkeros** [comment]
Glad it works for you!  Yeah the whole MS-DOS enabling adlib/soundblaster emulation is sort of a hidden semi-unsupported VMware feature.  You can enable it by hacking VM machine config files too, but for this case just selecting MS-DOS is easier.
